name: "Publish"

on:
  release:
    types: [released] # triggered on main branch releases

jobs:
  publish_to_micorsoft_edge_add_ons:
    name: "Publish To Microsoft Edge Add-ons"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v3
      - name: "📥 Download Latest Release Asset"
        uses: ./.github/actions/download-latest-release-asset
        with:
          asset_prefix: "kibisis-edge"
          github_token: ${{ secrets.WRITE_REPOS_TOKEN }}
      - name: "🚀 Publish"
        uses: ./.github/actions/publish-to-microsoft-edge-add-ons
        with:
          # set in the Settings > Secrets and variables > Actions > Secrets
          access_token_url: ${{ secrets.MICROSOFT_EDGE_ADD_ONS_API_ACCESS_TOKEN_URL }}
          client_id: ${{ secrets.MICROSOFT_EDGE_ADD_ONS_API_CLIENT_ID }}
          client_secret: ${{ secrets.MICROSOFT_EDGE_ADD_ONS_API_CLIENT_SECRET }}
          product_id: ${{ vars.MICROSOFT_EDGE_ADD_ON_PRODUCT_ID }}
          zip_file_name: kibisis-edge.zip

  publish_to_firefox_add_ons:
    name: "Publish To Firefox Add-ons"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v3
      - name: "📥 Download Latest Release Asset"
        uses: ./.github/actions/download-latest-release-asset
        with:
          asset_prefix: "kibisis-firefox"
          github_token: ${{ secrets.WRITE_REPOS_TOKEN }}
      - name: "🚀 Publish"
        uses: ./.github/actions/publish-to-firefox-add-ons
        with:
          addon_id: ${{ vars.FIREFOX_ADD_ONS_ID }}
          jwt_issuer: ${{ secrets.FIREFOX_ADD_ONS_API_JWT_ISSUER }}
          jwt_secret: ${{ secrets.FIREFOX_ADD_ONS_API_JWT_SECRET }}
          zip_file_name: kibisis-firefox.zip
