name: "Publish To Microsoft Edge Add-ons"

on:
  release:
    types: [released] # triggered on main branch releases

env:
  asset_prefix: "kibisis-edge"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v3
      - name: "📥 Download Latest Release Asset"
        uses: ./.github/actions/download-latest-release-asset
        with:
          asset_prefix: ${{ env.asset_prefix }}
          github_token: ${{ secrets.WRITE_REPOS_TOKEN }}
      - name: "🚀 Publish"
        env:
          # set in the Settings > Secrets and variables > Actions > Secrets
          MICROSOFT_EDGE_ADD_ONS_API_CLIENT_ID: ${{ secrets.MICROSOFT_EDGE_ADD_ONS_API_CLIENT_ID }}
          MICROSOFT_EDGE_ADD_ONS_API_CLIENT_SECRET: ${{ secrets.MICROSOFT_EDGE_ADD_ONS_API_CLIENT_SECRET }}
          MICROSOFT_EDGE_ADD_ONS_API_ACCESS_TOKEN_URL: ${{ secrets.MICROSOFT_EDGE_ADD_ONS_API_ACCESS_TOKEN_URL }}
        run: |
          ./bin/publish_to_microsoft_edge_add_ons.sh ${{ vars.MICROSOFT_EDGE_ADD_ON_PRODUCT_ID }} ${{ env.asset_prefix }}.zip

