name: "Refresh Chrome Web Store API Token"

on:
  schedule:
    # every day at 01:00
    - cron:  "0 1 * * *"

jobs:
  refresh:
    name: "Refresh"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "♻️ Refresh"
        env:
          # set in the Settings > Secrets and variables > Actions > Secrets
          CHROME_WEB_STORE_API_CLIENT_ID: ${{ secrets.CHROME_WEB_STORE_API_CLIENT_ID }}
          CHROME_WEB_STORE_API_CLIENT_SECRET: ${{ secrets.CHROME_WEB_STORE_API_CLIENT_SECRET }}
          CHROME_WEB_STORE_API_REFRESH_TOKEN: ${{ secrets.CHROME_WEB_STORE_API_REFRESH_TOKEN }}
        run: |
          ./bin/refresh_chrome_web_store_token.sh

