name: "Release"

on:
  push:
    branches:
      - beta
      - main

jobs:
  ##
  # install
  ##

  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "🔧 Setup"
        uses: ./.github/actions/use-dependencies

  ##
  # release
  ##

  release:
    name: "Release"
    needs: [install]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v4
      - name: "📦 Install yq"
        uses: ./.github/actions/install-yq
      - name: "🔧 Setup"
        uses: ./.github/actions/use-dependencies
      - name: "📝 Create .env file"
        uses: ./.github/actions/create-env-file
        with:
          provider_id: ${{ vars.PROVIDER_ID }}
          walletconnect_project_id: ${{ secrets.WALLETCONNECT_PROJECT_ID }}
      - name: "🔖 Release"
        env:
          # appears on the release commits
          GIT_AUTHOR_NAME: agoralabs-bot
          GIT_AUTHOR_EMAIL: tech@agoralabs.sh
          GIT_COMMITTER_NAME: agoralabs-bot
          GIT_COMMITTER_EMAIL: tech@agoralabs.sh
          # used to push the release commit and create the tags
          GITHUB_TOKEN: ${{ secrets.WRITE_REPOS_TOKEN }}
        run: yarn semantic-release
